config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root 'pages#index'
  get '/admin-page', to: 'pages#admin'
  get '/admin-phone-list', to: 'pages#adminphones'

  resources :phones
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :phones
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :admin
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_admin!, only: [:admin, :adminphones]
  def index
    @phones = Phone.all
  end

  def adminphones
    @phones = Phone.all
  end

end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  before_action :authenticate_admin!, except: [:show]
  def new
    @phone = Phone.new
  end

  def create
    @phone = current_admin.phones.build(phone_params)
    if @phone.save
      redirect_to admin_page_path
    end
  end

  def show
    @phone = Phone.find(params[:id])
  end

  def edit
    @phone = Phone.find(params[:id])
  end

  def update
    @phone = Phone.find(params[:id])
    @phone.update(phone_params)
    if @phone.save
      redirect_to phone_path(@phone.id)
    end
  end

  def destroy
    @phone = Phone.find(params[:id])
    @phone.destroy
    redirect_to admin_page_path
  end

  private
    def phone_params
      params.require(:phone).permit(:admin_id, :price, :brand, :model, :materials, :color, :os, :displaysize, :displaytype, :displayresolution, :soc, :frequency, :gpu, :rom, :ram, :sims, :maincam, :frontcam, :videoresolution, :focus, :moreaboutcam, :battery, :fastcharge, :wireless, :year, :interfaces, :dimensions, :mass, :more, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmartphoneShop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div style="top: 0px; left: 0px; width: 100%;
    position: fixed;
    top: 0px;
    left: 0px;
    padding: 4px;
    background-color: white;
    border-bottom-left-radius: 16px;
    border-bottom-right-radius: 16px;
    vertical-align: middle;
    box-shadow: 4px 2px 7px 3px rgba(0, 0, 0, 0.44);">
      <% if admin_signed_in? %>
        <strong><%= current_admin.email %>(admin)</strong> <%= link_to "Profile", edit_admin_registration_path %> <%= link_to "Log out", destroy_admin_session_path, method: :delete %>
        <%= link_to "View phones", admin_phone_list_path %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/pages/admin.html.erb
<h2 style="margin-top: 40px">Adminka</h2>


<p>
  some statistics about workers
</p>

app/views/pages/adminphones.html.erb
<h2 style="margin-top: 40px">Smartphones</h2>
<p><%= link_to "Add phone", new_phone_path %><br>
<% if @phones == [] %>
    <p>No phones</p>
<% else %>
    <% @phones.each do |phone| %>
       <p><b><%= phone.brand %></b> <%= phone.model %> | <i><%= phone.price %> UAN</i> <%= link_to "Show", phone_path(phone.id) %> <%= link_to "Edit", edit_phone_path(phone.id) %> <%= link_to "Delete", phone_path(phone.id), method: :delete %><br>
    <% end %>
<% end %>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/phones/edit.html.erb
<div style="margin-top: 40px"/>
<%= form_for @phone, url: phone_path do |f| %>
Brand:
<%= f.text_field :brand %><br>
Model:
<%= f.text_field :model %><br>
Price:
<%= f.number_field :price %><br>
Materials:
<%= f.text_field :materials %><br>
Color:
<%= f.text_field :color %><br>
OS:
<%= f.text_field :os %><br>
Display diagonal (inches):
<%= f.text_field :displaysize %><br>
Display type:
<%= f.text_field :displaytype %><br>
Display resolution:
<%= f.text_field :displayresolution %><br>
System on a Chip:
<%= f.text_field :soc %><br>
Frequency:
<%= f.text_field :frequency %><br>
GPU:
<%= f.text_field :gpu %><br>
ROM storage:
<%= f.number_field :rom %><br>
RAM storage:
<%= f.number_field :ram %><br>
Number of SIM cards:
<%= f.number_field :sims %><br>
Main camera:
<%= f.text_field :maincam %><br>
Front camera:
<%= f.text_field :frontcam %><br>
Video resolution:
<%= f.text_field :videoresolution %><br>
Camera focus type:
<%= f.text_field :focus %><br>
More about cam:
<%= f.text_area :moreaboutcam, size: "60x12" %><br>
Battery size (mAh):
<%= f.number_field :battery %><br>
Fast charge:
<%= f.text_field :fastcharge %><br>
Wireless interfaces:
<%= f.text_area :wireless, size: "60x12" %><br>
Wire interfaces:
<%= f.text_field :fastcharge %><br>
Year:
<%= f.number_field :year %><br>
Dimensions:
<%= f.text_field :dimensions %><br>
Mass:
<%= f.number_field :mass %><br>
More:
<%= f.text_area :more, size: "60x12" %><br>
Description:
<%= f.text_area :description, size: "60x12" %><br>
<%= f.submit "Submit" %>
<% end %>

app/views/phones/new.html.erb
<div style="margin-top: 40px"/>
<%= form_for @phone, url: {action: "create"} do |f| %>
Brand:
<%= f.text_field :brand %><br>
Model:
<%= f.text_field :model %><br>
Price:
<%= f.number_field :price %><br>
Materials:
<%= f.text_field :materials %><br>
Color:
<%= f.text_field :color %><br>
OS:
<%= f.text_field :os %><br>
Display diagonal (inches):
<%= f.text_field :displaysize %><br>
Display type:
<%= f.text_field :displaytype %><br>
Display resolution:
<%= f.text_field :displayresolution %><br>
System on a Chip:
<%= f.text_field :soc %><br>
Frequency:
<%= f.text_field :frequency %><br>
GPU:
<%= f.text_field :gpu %><br>
ROM storage:
<%= f.number_field :rom %><br>
RAM storage:
<%= f.number_field :ram %><br>
Number of SIM cards:
<%= f.number_field :sims %><br>
Main camera:
<%= f.text_field :maincam %><br>
Front camera:
<%= f.text_field :frontcam %><br>
Video resolution:
<%= f.text_field :videoresolution %><br>
Camera focus type:
<%= f.text_field :focus %><br>
More about cam:
<%= f.text_area :moreaboutcam, size: "60x12" %><br>
Battery size (mAh):
<%= f.number_field :battery %><br>
Fast charge:
<%= f.text_field :fastcharge %><br>
Wireless interfaces:
<%= f.text_area :wireless, size: "60x12" %><br>
Wire interfaces:
<%= f.text_field :fastcharge %><br>
Year:
<%= f.number_field :year %><br>
Dimensions:
<%= f.text_field :dimensions %><br>
Mass:
<%= f.number_field :mass %><br>
More:
<%= f.text_area :more, size: "60x12" %><br>
Description:
<%= f.text_area :description, size: "60x12" %><br>
<%= f.submit "Add" %>
<% end %>

app/views/phones/show.html.erb
<div style="margin-top: 40px"/>
<%= @phone.brand %> <%= @phone.model %>
<p><small>Description:</small></p>
<%= @phone.description %>